[package]
name = "kill_me"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.13.0" }
bevy_embedded_assets = "0.10.2"
bevy_pixel_camera = "0.13.0"




